### PR TITLE
fixed android bug cursor

### PR DESCRIPTION
**Pull request by hoangdaicntt**

### CODE REVIEW

**Review by RivasCVA — CHANGES_REQUESTED** [review]
This change seems to cause issues on iOS. The reason `useRef` was originally used was because there seems to be a bug with React Native regarding the `selection` and `onSelectionChange` props.

This is what happens on iOS with this change:



It seems to be due to multiple re-renders occurring concurrently, one for `value` and one for `selection`. View this [issue](https://github.com/expo/expo/issues/8071#issuecomment-621184957) for more details.

I am assuming that this does not occur on Android, but I cannot test it since I do not have Android Studio set up. This also means I am not too familiar with the bugged Android cursor issue being reported. Any help to address this would be appreciated.

**Comment by andrepith** [comment]
I need only `textAlignVertical: 'top'` to fix cursor center aligned on android devices

**Comment by CapitanRedBeard** [comment]
I tested out @andrepith comment above ^ And only adding the `textAlignVertical: 'top'` to the input styles does the trick and doesn't mess up iOS.

Here is a PR with only that change: #10

**Comment by RivasCVA** [comment]
Resolved, as of now, through PR #10.

**Pull request closed without merging**
